
spring:
  datasource:
    driver-class-name: your driver-class-name
    username: your username
    password: your password
    url: your url


#  AppId 和 AppSecret
weixin:
  miniapp:
    configs:
      - appid: your appid
        secret: your secret
